# Sync wave -2. Proxmox CSI (Helm, OCI). You MUST point existingConfigSecret at a Secret
# that already exists on the target cluster (created by your bootstrap, Sealed Secrets, etc.).
# Default name is generic; override with a Kustomize patch (see examples/).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-proxmox
  source:
    repoURL: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    path: "."
    targetRevision: 0.5.7
    helm:
      values: |
        existingConfigSecret: "proxmox-csi-config"
        existingConfigSecretKey: config.yaml
        config:
          features:
            provider: proxmox
          clusters: []
        storageClass:
          - name: proxmox-data-xfs
            storage: local-lvm
            reclaimPolicy: Delete
            fstype: xfs
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
